[build]
  command = "npm run build"  # o el comando que uses para compilar tu sitio (puede ser nulo si usas solo archivos estáticos)
  publish = "build"          # carpeta donde están tus archivos listos para publicar, como 'build' o 'dist'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
